source 'https://github.com/CocoaPods/Specs.git'

def import_pods
    pod "CDTDatastore/SQLCipher", :path => "../"
    pod "Unirest", :git => 'https://github.com/mikerhodes/unirest-obj-c.git'
    pod 'TRVSMonitor'
    pod 'NSData+Base64'
end

target :ios do
    platform :ios, '7.0'
    link_with 'RA_Tests_iOS', 'ReplicationAcceptanceAppTests'
    import_pods
end

target :osx do
    platform :osx, '10.9'
    link_with 'RA_Tests_OSX'
    import_pods
end
