source 'https://github.com/CocoaPods/Specs.git'

 xcodeproj 'Tests'
 workspace '../CDTDatastore'

def import_pods
    pod "CDTDatastore", :path => "../"
    pod "MRDatabaseContentChecker"
    pod 'Specta'
    pod 'Expecta'
    pod 'OCMock'
    pod 'OHHTTPStubs'
end

target :ios do
    platform :ios, '7.0'
    link_with ['Tests']
    import_pods
end

target :osx do
  platform :osx, '10.9'
  link_with 'Tests OSX'
  import_pods
end
