 xcodeproj 'Tests'
 workspace '../CDTDatastore'

def import_pods
    pod "CDTDatastore", :path => "../"
    pod "MRDatabaseContentChecker"
end

target :ios do
    platform :ios, '7.0'
    link_with ['Tests']
    import_pods
end

target :osx do
  platform :osx, '10.8'
  link_with 'Tests OSX'
  import_pods
end
