 xcodeproj 'Tests'
 workspace '../CDTDatastore'

def import_pods
    pod "CDTDatastore", :path => "../"
    pod "FMDB", :git => "https://github.com/mikerhodes/fmdb.git"
end

target :ios do
     platform :ios, '7.0'
     link_with ['Tests']
    import_pods
end

target :osx do
  platform :osx, '10.9'
  link_with 'Tests OSX'
  import_pods
end
