source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'EncryptionTests'

def import_pods
  pod "CDTDatastore/SQLCipher", :path => "../"
end

target :ios do
    platform :ios, '7.0'
    link_with 'Encryption Tests'
    import_pods
end

target :osx do
  platform :osx, '10.8'
  link_with 'Encryption Tests OSX'
  import_pods
end
