# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "image_share" do

pod "CDTDatastore", :git => 'https://github.com/cloudant/CDTDatastore.git'

end

target "image_shareTests" do

pod "CDTDatastore", :git => 'https://github.com/cloudant/CDTDatastore.git'

end

