source 'https://github.com/CocoaPods/Specs.git'
xcodeproj 'Project'

def import_pods
    use_frameworks!
    pod "CDTDatastore", :path => "../"
end

target :Project do
    platform :ios, '8.0'
    import_pods
end
